name: Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      bucket: staging.lazysheet.com
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DISTRIBUTION_ID: ${{ secrets.STAGING_DISTRIBUTION_ID }}
    environment: staging
