name: Deploy Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      bucket: lazysheet.com
      environment: production
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DISTRIBUTION_ID: ${{ secrets.PROD_DISTRIBUTION_ID }}